[tool.ruff]
line-length = 79
target-version = "py311"
# If you want isort-style import ordering via Ruff:
extend-select = ["I"]

[tool.ruff.lint]
# If you keep hitting W605 (escape sequences), either fix strings or ignore:
ignore = ["W605"]

[tool.ruff.format]
# Enable Ruff's formatter instead of Black:
quote-style = "preserve"
indent-style = "space"

[tool.mypy]
python_version = "3.11"
disallow_untyped_defs = true
no_implicit_optional = true
warn_unused_ignores = true
warn_return_any = true

# If you INSTALL stubs (recommended):
[mypy-pandas.*]
ignore_missing_imports = false
[mypy-seaborn.*]
ignore_missing_imports = false

# If you prefer NOT to install stubs, flip both to true.
